### ISSUE TITLE
Diseñar el Query Language

### ISSUE THREAD

**Issue by damarizz** [proyectitos-fisi/elenadb#3]
- [ ] El sistema debe permitir a los desarrolladores comunicarse con la base de datos a través de un lenguaje de queries estandarizado.

**Comment by paoloose** [comment]
Diseño por @pandadiestro 

![Image](https://github.com/proyectitos-fisi/elenadb/assets/98111143/0b545444-b76a-4da5-8f7f-639cf077a2d2)
